### PR TITLE
Docker updates

### PR DESCRIPTION
**Pull request by jbrady42**
Re-opening this so we can move hosting forward. I have seen a few users having trouble hosting, and had quite a time getting it set up myself the first time. These changes represent a fairly standard way of web hosting and I think they are very beneficial to new users. 

As I mentioned in the last PR the port change on the clients is intentional in order to use standard web ports (443 in prod) for hosting. If you are having issues with your hosting I would be glad to go through it and work out changes to support it.

I have been hosting using this docker setup for weeks now and have had zero issue. Please update with what issues you are running into so we can get this merged and out to the community.

### CODE REVIEW

**Comment by adwpc** [comment]
I tested on my mac and found some problem:
1. this pr remove the js and dart 8443 and use caddy to proxy /ws to biz:8443
so i think must use caddy in scripts/webStart.sh

2. I download caddy by `brew install caddy`, but this can only download the 1.0.5
Then i download 2.0RC.3 from https://github.com/caddyserver/caddy/releases
I prefer brew because it's easy to use in scripts/*.sh

3. when i run 2.0, got some error
```
./caddy run -config docker/Caddyfile   22:23:41
2020/05/03 14:27:31.077	INFO	using provided configuration	{"config_file": "docker/Caddyfile", "config_adapter": ""}
```

**Comment by jbrady42** [comment]
Have you tried running this using only the docker-compose setup and the instructions listed in this branch?

For external or production hosting the node server should not be started. All js builds and proxying is handled by the web container, so all that is needed is to configure docker-compose and bring the stack up.

For local hosting I have been using the local.Caddyfile and the web container to provide js serving and biz socket proxy. This is similar to the prod config except SSL is not enabled and the exposed port is 8080 instead of 80 and 443.


For you #3 point I get a similar info message when booting my server, but everything works correctly.
```
{"level":"info","ts":1588521619.5022938,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}

```

Can you give it a shot just using the docker-compose setup and web container without the `webStart.sh` script.

**Comment by adwpc** [comment]
1. I tested local hosting, it worked
1) uncomment build lines in docker-compose.yml
2) rm node_modules
3) docker-compose build
4) docker-compose up

2. I develop go code with scripts, diffcult to devleop in docker
I want to make scripts work, i found the difference between docker and scripts is :
docker use caddy proxy /ws to 8443

 maybe i should ask @cloudwebrtc how to make 8443 configalbe
image

**Comment by adwpc** [comment]
By the way:
Im doing this:
https://github.com/pion/ion/issues/157

**Comment by tarrencev** [comment]
With the new js sdk, the ws endpoint is now configurable. We will need to update the web app to use it though.

**Comment by jbrady42** [comment]
Going to merge this for now since we are moving the client apps and sdk out of the Ion repo. We will need to revisit front end hosting for the JS demo app when its final location is settled.

**Comment by adwpc** [comment]
ok
maybe we need a new repo ion-app-web？or ion-web？

**Pull request merged**
