### PR TITLE
Add Python script to stress test the Ion web stack

### PR DESCRIPTION
**Pull request by barronbud**
#### Description
Simple Python script that uses Selenium and Chromedriver to generate multiple user sessions and stress test the Ion JS Demo code and underlying Docker containers.

Useful to diagnose #135.

### CODE REVIEW

**Comment by Sean-Der** [comment]
This is amazing! We should get this running in travis as well :)

**Comment by jsays** [comment]
Thanks @Sean-Der. This recreates our issue (#135) on ion reliably when CLIENTS is cranked to 10...though interestingly we can sneak a few more in by adjusting the delay a bit.

**Comment by leewardbound** [comment]
Hi, I've created another version of this for my own needs -- I like the selenium approach, but I needed something containerized and with file-based webcam support (I want to someday automate fake peers running on servers in various locations under different conditions and collect telemetry data).

I've managed to use the `buildkite/puppeteer` image to successfully join an Ion room using a mjpeg for the webcam input. I wrote a really simple puppeteer script for the Ion Conference that accepts ROOM, USER and URL as environment variables, and allows you to choose any mjpeg you want for webcam feed.  You can add a fake user to any Ion room with the following 1-liner (you need ~/webcam.mjpeg to exist for this to work, microphone.wav is optional):

```
docker run -ti \
  -v "$HOME/webcam.mjpeg:/webcam.mjpeg" \
  -v "$HOME/microphone.wav:/microphone.wav" \
  -e NAME=testbuddy \
  -e URL=https://conference.pion.ly:8080/ \
  -e ROOM=MyRoomName \
  buildkite/puppeteer:latest \
  bash -c "wget https://gist.githubusercontent.com/leewardbound/4415994057a4b84fe8b47b629dd4a04a/raw/cd345abd5e8d1f6acb1add669ba533cff3275915/puppeteer-peer.js -O /peer.js; node /peer.js"
```

Due to hosting the file on my gist like a hack, it is a very ugly command, but it works.

I'm glad to contribute the `puppeteer-peer.js` file to the `pion/ion` repository if it would be useful here, just tell me where to put it!

I have tested as many as 5 peers at once running on a single $60 "Compute" Linode; it made the server very warm and unhappy but it worked.

**Comment by adwpc** [comment]
LGTM!

**Comment by adwpc** [comment]
@barronbud i tested this script, but chrome cost a lot of cpu.
Maybe i should look at this one
https://github.com/jbrady42/ion-vid
@jbrady42

**Comment by jbrady42** [comment]
It depends on what you are trying to test. It's fairly easy to modify my client to drive up load on the ion server. Multiple clients sending streams in multiple rooms, etc... . But it needs a matched consumer on the other side to really work. If we just use a go webrtc sink that throws away the received data, that would work, but definitely does not test the front end client. However it should work fine for a brute force load testing tool against the sfu.

**Comment by adwpc** [comment]
yep, sfu need some load testing

**Pull request merged**
