### PR TITLE
fix(biz): race condition for room & peer

### PR DESCRIPTION
**Pull request by hn8**
#### Description
1. When the same client rejoins with the same uid, delPeer in defer of exiting goroutine may delete the newly created peer with the same uid.
2. Fix RWMutex use in BizServer.createRoom()/.getRoom()
3. Room.getPeers() return was not thread-safe to iterate
4. Peer.send() may be possibly out-of-order for the blocking repCh.

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
LGTM

**Review by cloudwebrtc — APPROVED** [review]

**Comment by hn8** [comment]
@cloudwebrtc Hi, I pushed 2 more commits to remove race condition and also reduce the chance of out-of-order message and goroutine churn for peer.send(). Btw, do I need to fix docker first to pass Github Actions?

**Comment by hn8** [comment]
Also fixed Github Actions issue from HEAD

**Comment by hn8** [comment]
@cloudwebrtc linting fails because grpc.CustomCodec() is depreciated, will need to migrate to encoding.RegisterCodec
```
-	srv := grpc.NewServer(
-		grpc.CustomCodec(nrpc.Codec()),
-		grpc.UnknownServiceHandler(nproxy.TransparentHandler(sig.Director)))
+	srv := grpc.NewServer(
+		grpc.UnknownServiceHandler(nproxy.TransparentHandler(sig.Director)))
+	encoding.RegisterCodec(nrpc.Codec())
```

But nrpc.Codec() return grpc.Codec, will need to add Name() method to also satisfy encoding.Codec interface, like:
https://github.com/google/flatbuffers/blob/master/go/grpc.go#L22-L34

Do I need to open a PR in github.com/cloudwebrtc/nats-grpc first? Thanks

**Comment by cloudwebrtc** [comment]
Yeah, you can open PR to nats-grpc. @hn8

**Pull request merged**
