### PR TITLE
improve Dockerfile steps

### PR DESCRIPTION
**Pull request by sashaaro**
#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by adwpc** [comment]
Thanks, amazing work!

**Comment by sashaaro** [comment]
This pr contents separate step for download go modules without source code therefore this step will be cached until `go.mod` `sum.mod` are changed
Official registry etcd image
Replace nodejs http-server to nginx

it was working before, but now isn't. In master branch it's not too for me. rabbitmq start slowly and up command failed, probably healthcheck directive is incorrect
If up rabbitmq only and then rest ones with delay it work but participants can not see each other. I don't know why. 
I don't have time for make done it now

**Comment by sashaaro** [comment]
@adwpc It's done

**Comment by adwpc** [comment]
LGTM！Thanks！Sorry for late

**Pull request merged**
